### ISSUE TITLE
Klok optisch puntje

### ISSUE THREAD

**Issue by rbijlsma** [redmaner/MIUI7-XML-DUTCH#107]
Bij de klok zijn ook nog een paar dingen die ik niet zo mooi vind.

- de tekst van de knoppen 'Wekker toevoegen' en 'Instellingen' staan te dicht bij elkaar.
- is het niet mooier om de titel wekkers te veranderen in 'Alarm'
- dan zou je bij de eerste knop de tekst 'Nieuw Alarm' kunnen gebruiken.

![screenshot_2015-11-15-21-24-42_com android deskclock](https://cloud.githubusercontent.com/assets/15678627/11170801/6e0def7e-8bdf-11e5-9435-e3c2d0958264.png)

**Comment by MannyRibo** [comment]
Ik heb de titel linksboven 'Wekkers' gelaten. 
De tekst onder de + knop veranderd naar 'Nieuwe wekker'. 
Dat scheelt 3 letters dus laat me weten of de tekst zo niet meer te dicht op elkaar staat.
