### ISSUE TITLE
Rabo bankieren app werkt niet meer sinds 5.11.5

### ISSUE THREAD

**Issue by Morph3u55** [redmaner/MIUI7-XML-DUTCH#114]
De Rabo bankieren app werkt niet meer sinds update 5.11.5
Ik heb al contact gehad met de Rabobank hierover, maar het verwijderen opnieuw registeren van de telefoon e.d. heeft niet geholpen.
De app crasht gelijk bij het opstarten. (voor het kiezen van een profiel)
Toestel MI4c ROM 5.11.12/13

**Comment by MannyRibo** [comment]
Werkt het wel met de telefoon op Engels dan? Zo niet is het geen probleem in de vertaling en kunnen wij er ook niets aan doen.

**Comment by Morph3u55** [comment]
Bedankt voor de snelle reactie.

Dat werkt helaas ook niet. (engels)
Dit ligt aan de ROM zelf en niet aan de vertaling.
Hoe en waar kan ik dit het beste melden?


Op 18 november 2015 23:18 schreef Manny <notifications@github.com>:

**Comment by MannyRibo** [comment]
Ik denk op de originele miui website. Maar dan wel met een log, anders kunnen ze er niks mee.

**Comment by MannyRibo** [comment]
In de tussentijd kan je misschien terug naar een vorige versie waar het nog wel werkte als je mobiel bankieren echt niet kan missen.
