### ISSUE TITLE
taal niet beschikbaar in hoofdmenu

### ISSUE THREAD

**Issue by MathijsBesten** [redmaner/MIUI7-XML-DUTCH#128]
Als bij instellingen gezocht wordt om de taal in te stellen is de optie "Dutch" of "Nederlands" niet beschikbaar. ik hoop dat dit ook wordt gefixt. :+1:

**Comment by Cueie** [comment]
Staat in instellingen>extra instellingen>taal en invoer

**Comment by redmaner** [comment]
Ik neem aan dat dit geen probleem meer is, issue #128 bij deze gesloten
