### ISSUE TITLE
 ROM 5.12.17 mist vertalingen

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI7-XML-DUTCH#151]
Bij instellingen mi- account heet de nieuwe instelling back-up device en in nl staat back-up aaps en de pagina daar achter is helemaal niet vertaald . verder mis ik bij de nieuwe weather app wat vertalingen . hij is nu half en en half nl

**Comment by monsieurpaulu** [comment]
![screenshot_2015-12-18-07-56-01_com miui weather2](https://cloud.githubusercontent.com/assets/7716225/11891231/e27d6326-a55c-11e5-93a3-c9c0c2ca0cf9.png)
![screenshot_2015-12-18-07-44-37_com miui cloudservice](https://cloud.githubusercontent.com/assets/7716225/11891234/eb46592c-a55c-11e5-9159-31ea45f1d9cc.png)

**Comment by monsieurpaulu** [comment]
![screenshot_2015-12-18-07-44-45_com miui cloudbackup](https://cloud.githubusercontent.com/assets/7716225/11891245/083f3170-a55d-11e5-8e1c-a162d91247ba.png)

**Comment by MannyRibo** [comment]
Dankjewel, wordt aan gewerkt. Mag ik weten welke telefoon je hebt?

**Comment by monsieurpaulu** [comment]
Jazeker gaat om een MI4c , jullie bedankt voor het vertalen ;)

**Comment by MannyRibo** [comment]
Opgelost. Graag met de volgende update kijken of het allemaal oke is.

**Comment by x2tharay** [comment]
Ik heb nog iets wat nog niet vertaald is.
Bij instellingen staat sound & vibration.
Versie 5-12-17 op mijn mi4i

**Comment by MannyRibo** [comment]
Heb ik toevallig al opgelost gisteren. Er was iemand in de xiaomi.eu thread die daarvan een screenshot had gepost, weet niet of jij dat was.

**Comment by x2tharay** [comment]
Nee, maar in ieder geval bedankt!

**Comment by MannyRibo** [comment]
Geen probleem. Blijf alsjeblieft fouten melden als je ze tegenkomt.
