### ISSUE TITLE
De muziek app

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI7-XML-DUTCH#160]
In de muziek app staat bij download mappen maar dit past niet echt mooi.
Is dit aan te passen?
Misschien naar alleen het woord "map"

Vriendelijke groet.

**Comment by MannyRibo** [comment]
Ik zal er één van de komende dagen naar kijken. Als je er alleen maar 'map' van maakt zal het niet echt meer logisch zijn. Misschien dat we het één en ander kunnen verkorten, want het komt volgens mij omdat de woorden artiesten en nummers allebei ook langer zijn dan de Engelse vertalingen. Daardoor blijft er te weinig ruimte over voor 'mappen' om op één regel te passen.

**Comment by x2tharay** [comment]
Zou mooi zijn ;)
Bedankt alvast.

**Comment by MannyRibo** [comment]
Ik zal binnenkort kijken, al weet ik niet zo goed wat we er het beste van kunnen maken. Jij moet dan even kijken of het is opgelost, want ik krijg geen weekly updates meer voor m'n mi4.

**Comment by x2tharay** [comment]
Helemaal tevreden!

**Comment by MannyRibo** [comment]
Heb je wel gekeken of het is opgelost? Ik heb hier namelijk nog niks aan gedaan, ik weet niet zo goed wat ik er het beste van kan maken.
