### ISSUE TITLE
Email app repl

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI7-XML-DUTCH#167]

**Comment by x2tharay** [comment]
Sorry bij de email app is een email linksonder in het menu reply en forward niet vertaald.
Mi4i versie  5.12.42.
Groet

**Comment by MannyRibo** [comment]
Heb je een screenshot? Ik zie zo niet wat je bedoelt.

**Comment by MannyRibo** [comment]
Laat maar, denk dat ik het al heb opgelost. Dankjewel en graag kijken met de volgende update of het verholpen is.

**Comment by x2tharay** [comment]
Top! Ga ik doen.

**Comment by x2tharay** [comment]
Opgelost.
Top!
