### ISSUE TITLE
Errors | Email.apk | PackageInstaller.apk | Settings.apk

### ISSUE THREAD

**Issue by usnkreal** [redmaner/MIUI7-XML-DUTCH#169]
Email.apk/res/values-nl/strings.xml:307: error: Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?

Email.apk/res/values-nl/strings.xml:307: error: Unexpected end tag string

PackageInstaller.apk/res/values-nl/strings.xml:150: error: Resource entry unknown_apps_dlg_text is already defined.

PackageInstaller.apk/res/values-nl/strings.xml:145: Originally defined here.

PackageInstaller.apk/res/values-nl/strings.xml:146: Originally defined here.

PackageInstaller.apk/res/values-nl/strings.xml:151: error: Resource entry unknown_apps_dlg_title is already defined.

Settings.apk/res/values-nl/strings.xml:49: error: Error parsing XML: not well-formed (invalid token)

**Comment by MannyRibo** [comment]
https://github.com/MannyRibo/MIUI7-XML-DUTCH/commit/2f8335b51bb6b31ab67e2e02b4e63adff596fd5c

Thanks
