### ISSUE TITLE
Gemiste oproep 

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI7-XML-DUTCH#181]
Bij een gemiste oproep krijg ik de tekst in het Engels in mijn vergrendelscherm en boven in het scherm.

**Comment by MannyRibo** [comment]
En die tekst is?

**Comment by x2tharay** [comment]
"Missed call"

**Comment by MannyRibo** [comment]
https://github.com/MannyRibo/MIUI7-XML-DUTCH/commit/e5e0c9dcc0ca346629080bdd25b7e32cf3e34c1e

**Comment by x2tharay** [comment]
Opgelost! Bedankt!
