### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by usnkreal** [redmaner/MIUI7-XML-DUTCH#186]
Contacts.apk/res/values-nl/strings.xml:642: error: Resource entry miprofile_name is already defined.
Contacts.apk/res/values-nl/strings.xml:633: Originally defined here.

**Comment by MannyRibo** [comment]
https://github.com/MannyRibo/MIUI7-XML-DUTCH/commit/4c899dd72db1d28476b4c60312907184fedf242a
