### ISSUE TITLE
Vertaling in Veiligheid app 

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI7-XML-DUTCH#200]
In de veiligheid app "zwarte lijst" is een deel niet vertaald bij de keuze "blocked numbers" rechts bovenin. In dit menu zijn er wat vertalingen nodig.
Alvast bedankt.

**Comment by MannyRibo** [comment]
Zou je screenshots kunnen geven die alle niet vertaalde woorden/zinnen laten zien? Dankjewel.

**Comment by Cueie** [comment]
Nu reeds vertaald
