### ISSUE TITLE
Gemiste vertalingen

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI7-XML-DUTCH#217]
In de file Explorer app staan wat gemiste vertalingen bovenin.
"Recent" "categories" en "Phone"

En onderin staat basic apps

**Comment by Cueie** [comment]
Ik denk dat die nu zullen vertaald zijn .
Zijn nu pas bijgevoegd in de update.
Bij nog onvertaalde of verkeerde vertalingen laat maar weten
