### ISSUE TITLE
Gallerij mist vertalingen

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI7-XML-DUTCH#227]
In de gallerij app mist er vertakkingen wanneer je de foto selecteert .

Er staat bv. Send ipv zend

**Comment by monsieurpaulu** [comment]
Oeps vertakkingen moet natuurlijk vertalingen zijn ;)

**Comment by x2tharay** [comment]
Ook in het menu van de gallerij app zijn er geen vertalingen.
;)

**Comment by Cueie** [comment]
Sorry voor deze, maar Ik doe de vertalingen en kan zelf just niet meer zien wat er nu al vertaald is of niet, want er zijn voor mijn toestel geen updates meer.
Bij mij heb ik die wel vertaald staan.
Zal er eens naar kijken, maar kan niks beloven

**Comment by monsieurpaulu** [comment]
Kan ik met iets helpen ?

**Comment by Cueie** [comment]
Het zal wel lukken zo.
Je wel melden wat er niet gedaan, verkeerd of niet vertaald is.
Voor alles wat je melde wordt aan gewerkt.
Je kan dit mij persoonlijk melden via http://xiaomi.eu/community/members/cueie.93017/ in een conversatie. 
Alvast bedankt
Cueie
