### ISSUE TITLE
Muziek app 

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI7-XML-DUTCH#229]
In de muziek app bij instellingen zijn er geen vertalingen.
-Service and settings
More and advance settings

**Comment by Cueie** [comment]
De muziek app geeft geen updates meer gehad bij mij.
Kan het onmogelijk zien.

**Comment by MannyRibo** [comment]
Zijn dat alle onvertaalde zinnen of is er nog meer?
Screenshot zou helpen.
