### ISSUE TITLE
"Wachtwoord vergeten" showt in scherm <u> tags

### ISSUE THREAD

**Issue by ReTechNL** [redmaner/MIUI7-XML-DUTCH#254]
Device: Xiaomi Redmi Note 3 Pro
MIUI: Weekly 6.3.31 (Xiaomi.eu)

Locatie:
Instellingen > Schermbeveiliging  & Wachtwoord > Schermvergrendeling & vingerafdruk > (onder aan het scherm)
De label showt de volgende text: `<u>Wachtwoord vergeten<...`

Dit kom ik op meerdere locaties tegen dus mogelijk wordt deze label op meerdere locaties gebruikt.

![screenshot_2016-04-07-11-19-45_com android settings 1](https://cloud.githubusercontent.com/assets/5654247/14349973/c6a00e1c-fcc6-11e5-87ec-201070917e2f.png)

**Comment by MannyRibo** [comment]
Ik zie inderdaad dat dit op drie verschillende locaties voorkomt in de bestanden. Ik zal het vanavond veranderen. Dankjewel!

**Comment by ReTechNL** [comment]
Druk ff f5 hij laat het volgende zien
De label showt de volgende text: `<u>Wachtwoord vergeten<...`

**Comment by MannyRibo** [comment]
Klopt. Is een kwestie van de tekens ervoor en erna weghalen. Dan blijft het ook nog steeds een hyperlink, dus klikbaar.

**Comment by MannyRibo** [comment]
https://github.com/redmaner/MIUI7-XML-DUTCH/pull/256/commits/374994c6c188e655ab2e8a4441a36479f95e2c44

Graag kijken of het is opgelost als je hebt geupdatet. Ik weet niet of het wordt meegenomen in de 6.4.7 weekly.
