### ISSUE TITLE
Play store

### ISSUE THREAD

**Issue by brukske** [redmaner/MIUI7-XML-DUTCH#286]
Ik kan geen enkele app downloaden of updaten, zie scherm.

![image](https://cloud.githubusercontent.com/assets/18726729/14899717/ad1c5c16-0d8d-11e6-8fa2-70c3133a41de.png)

**Comment by MannyRibo** [comment]
Is geen vertaalfout, dus kunnen wij niks aan doen. Ga voor hulp naar de xiaomi.eu site.

**Comment by brukske** [comment]
ok, verkeerde plek dus! Bedankt voor de snelle reactie!
