### ISSUE TITLE
systeem zoekfunctie geeft Chinese zoekresultaten via "du" engine

### ISSUE THREAD

**Issue by ozfunghi** [redmaner/MIUI7-XML-DUTCH#323]
De zoekfunctie uit de systeem tray of wanneer je omhoog swiped, gebruikt een Chinese zoekengine en geeft dus Chinese resultaten weer. Een andere gebruiker heeft het probleem nagebootst door zijn taal (Spaans) te veranderen naar Nederlands. Eerst had hij het probleem niet (in Spaans), maar na de taal naar NL te veranderen, wel.

Afbeeldingen:
https://abload.de/img/1hpgi.jpg
https://abload.de/img/ksp0z.jpg

bevestiging andere gebruiker:
https://xiaomi.eu/community/threads/6-5-26-last-miui-7.31811/page-42#post-297409

(ik zit op een Redmi Note 2 Prime met 7.3.2.0 EU stable)

**Comment by MannyRibo** [comment]
Dankjewel! 
https://github.com/redmaner/MIUI7-XML-DUTCH/pull/324/files
Moet zo opgelost zijn denk ik.

**Comment by ozfunghi** [comment]
Leuk... hoe kan ik dit nu toepassen op mijn telefoon? Bestaat daar een tutorial voor? (Sorry,  ik heb dit nog nooit gedaan).

**Comment by MannyRibo** [comment]
De wijziging die ik net heb gedaan wordt toegepast op de rom bij de volgende update. Dit zal waarschijnlijk de eerstvolgende miui8 alpha zijn, maar aangezien jouw telefoon die niet krijgt heb jij daar niks aan. Wachten op een miui8 stable build kan ook wel even duren dus op z'n vroegst als je de miui8 beta flasht op 17 juni.

**Comment by ozfunghi** [comment]
Oh, ok. Bedankt. Dus dit kan niet "geflasht" worden ofzo. Jammer voorlopig, maar anderzijds ben ik al blij dat er anderen in de toekomst mee geholpen zijn.

**Comment by MannyRibo** [comment]
Eigenlijk maakt het helemaal geen verschil bedenk ik me nu, want volgende week vrijdag is er gewoon een weekly update. Als de weekly updates niet stil hadden gelegen door miui8 zat de wijziging er ook pas de volgende vrijdag in, net als nu. Ik weet niet of je echt koste wat kost de stable build wilt blijven draaien maar je kan overwegen om over te gaan op de weekly build, dan kan je als je dat wilt ook een beetje meehelpen met testen want je krijgt dan wekelijkse updates en als er iets niet goed vertaald is kan je dan hier meteen aangeven wat er niet goed is. Als je dus volgende vrijdag de weekly update flasht, is deze fout weg. Er is niet iets wat op dit moment deze wijziging kan doorvoeren op je telefoon, daarvoor moeten we wachten tot het in de volgende update zit verwerkt.

**Comment by ozfunghi** [comment]
Mja, ik had vooral de stable gekozen hopend dat een app waar mijn dochtertje graag op speelt (Miitomo van Nintendo) erop zou draaien. Die werkte wel op de Global stable, maar niet op de EU ROM die ik voordien had. Helaas dus ook niet op de EU stable. (Waarom niet, weet ik niet). In principe zou ik dus wel kunnen overstappen, al werd ik na 2 jaar weekly's op mijn Mi2 dat ook wel wat beu om elke week melding te krijgen om te updaten. Anderzijds stoort deze fout in de searchengine me ook niet zó hard dat ik er per se voor opnieuw wil gaan installeren etc. Ik zal er eens over nadenken ;) Als die app in de volgende update wel zou werken, dan zou ik het wel doen, haha.

**Comment by MannyRibo** [comment]
Ik ga volgende week vrijdag voor jou de miitomo app installeren en kijken of het werkt. Ik geef het weinig kans maar wie weet. Ik meen gelezen te hebben dat het iets te maken heeft met de roottoegang. Sowieso bedankt voor het melden want andere mensen hebben er inderdaad ook wat aan.

**Comment by ozfunghi** [comment]
Wow, top. Ik begrijp niet waarom die app wel werkt op de global stable, maar niet op EU stable, en mijn RMN2 is niet geroot. Ik zou't in elk geval appreciëren dat je er de tijd wil insteken, maar voel je zeker ook niet verplicht.

groetjes
