### ISSUE TITLE
bootloop in MIUI8..

### ISSUE THREAD

**Issue by fordrwd4ever** [redmaner/MIUI7-XML-DUTCH#329]
MIUI8 6.6.17
When i set the phone (Redmi Note 2) to Dutch language, it never stops booting (the 3 dots keep running..)

This is my bootlog when this happens :

First file is the short one, filtered by failures
The second one is filtered from errors and up
[miui8-dutch.txt](https://github.com/redmaner/MIUI7-XML-DUTCH/files/323015/miui8-dutch.txt)
[miui8-dutch2.txt](https://github.com/redmaner/MIUI7-XML-DUTCH/files/323016/miui8-dutch2.txt)

**Comment by ingbrzy** [comment]
double of https://github.com/redmaner/MIUI8-XML-DUTCH/issues/15
