### ISSUE TITLE
Vertaling mist bij opladen 

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI7-XML-DUTCH#330]
Bij het opladen mist de vertaling bij de statusbalk . (Mi4c)

Er staat charging ipv opladen?

![img_20160624_133240](https://cloud.githubusercontent.com/assets/7716225/16336798/5b459a92-3a10-11e6-861e-88576f55eef1.jpg)

**Comment by monsieurpaulu** [comment]
![img_20160624_133240](https://cloud.githubusercontent.com/assets/7716225/16336775/2ace3478-3a10-11e6-81e2-d51644095e7a.jpg)

**Comment by MannyRibo** [comment]
Graag rapporteren in de MIUI 8 repo. Als het goed is heb ik dit gisteren al opgelost maar is het net niet meegenomen in de 6.6.23 update.

**Comment by monsieurpaulu** [comment]
Oh ik zie het zit in 7  oeps ;-) maar ik draai de 6.6.23
