### ISSUE TITLE
Bewuste keuzes, of vergeten te vertalen in E-Mail

### ISSUE THREAD

**Issue by Casparvz** [redmaner/MIUI7-XML-DUTCH#332]
Als ik een email wil beantwoorden of doorsturen dan staat daar bij mij "reply" en "forward". Dit zouden Antwoord en Stuur door kunnen zijn?

Ik heb een Redmi 3s met laatste weekly.

**Comment by Cueie** [comment]
Zal er naar kijken en zien of ik de onbetaalde strings kan vinden.
Het is voor mij moeilijk om te weten wat of niet vertaald is, heb zelf geen toestel van Xiaomi meer

**Comment by MannyRibo** [comment]
Deze string mist in email.apk\strings.xml

`<string name="forward">Forward</string>`

En die

`<string name="reply">Reply</string>`
