### ISSUE TITLE
Bij opstellen email staat er "compose" als titel

### ISSUE THREAD

**Issue by Casparvz** [redmaner/MIUI7-XML-DUTCH#334]
Bij het opstellen of het beantwoorden van een email staat er boven (tussen de knoppen annuleren en verzenden in) de tekst compose. Dit zou opstellen moeten zijn.

Gaat om de weekly rom op een redmi 3s

**Comment by MannyRibo** [comment]
https://github.com/redmaner/MIUI8-XML-DUTCH/commit/e45ff6d7570c073c8ba07b87a2dc8654da5e3269
