### ISSUE TITLE
Bij gebruik van de klok widget "clock with weather 3" wordt luchtvochtigheid niet vertaald

### ISSUE THREAD

**Issue by Casparvz** [redmaner/MIUI7-XML-DUTCH#335]
Ik maak op mijn Redmi 3s gebruik van de klokwidget "clock with weather 3". Luchtvochtigheid staat er in het Pools (wilgotnosc). Ik weet niet of dit aan de widget ligt of aan de vertaling van Miui.

**Comment by MannyRibo** [comment]
Aan de widget
