### ISSUE TITLE
M4c Weather Ui Bug 6.11.10

### ISSUE THREAD

**Issue by flipperk** [redmaner/MIUI7-XML-DUTCH#338]
Bug in the weather UI (dutch) unfortunately (m4c): instead of hours in the hourly forcast in the weather app it shows minutes and some off numbers. Would be nice of corrected, thx

**Comment by MannyRibo** [comment]
Hier kan je nederlands praten. Hier is onze repository van MIUI 8: https://github.com/redmaner/MIUI8-XML-DUTCH
Daar kan je toekomstige problemen melden.

Hier hetzelfde probleem dat al gemeld is: https://github.com/redmaner/MIUI8-XML-DUTCH/issues/159

Hier de link voor de fix: https://github.com/redmaner/MIUI8-XML-DUTCH/commit/484c7d01a11c32b225468d4100300297d6f10e4e

Dankjewel.

**Comment by flipperk** [comment]
ah ik zie al dat ik het zelfs bij MIUI 7 heb gezet. Is link vanuit weekly update post op xiaomi eu

thx voor de hulp!
