### ISSUE TITLE
Vertaling in file Explorer app

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI7-XML-DUTCH#343]
In de file Explorer app tabblad categorieën staat "  " apps & folders "
Versie 7.2.9

**Comment by MannyRibo** [comment]
Niet in 7.2.16, en ook niet in 7.2.24.
Welke telefoon, en screenshot?
Als je hebt geupdatet en je hebt het nog steeds mag je het melden in de MIUI8 repo. 
Gegevens wissen van de specifieke app in instellingen wil wel eens helpen.
