### ISSUE TITLE
Fouten die gemeld zijn op xiaomi.eu

### ISSUE THREAD

**Issue by redmaner** [redmaner/MIUI7-XML-DUTCH#59]
Hi translators/Hallo vertalers.<br /><br />Ik zal hier een lijst neerzetten met zaken die niet (goed) zijn vertaald in versie: 5.10.8 op een Xiaomi Redmi Note 2 Prime.<br /><br /><b>Instellingen menu:</b><br /><br />1. SIM kaarten &amp; mobiele netwerken -&gt; Internationale roaming -&gt;<b>Overzeese</b> data roaming = Internationaal roaming<br />1b. Titel aanpassen van <b>Overzees</b> roaming = Internationaal roaming<br />2. Wi-Fi -&gt;Geavanceerde instellingen -&gt;Wi-Fi behouden in slaapstand -&gt;<b>Nooit(verbruikt meer mobiele data) = </b>Nooit (verhoogd datagebruik)<br />2b. <b>Alleen indien aangesloten</b> = Indien aan de oplader of Tijdens het opladen<br />3. Thema's -&gt; <b>Gedownloade</b> = Gedownload of Offline of Lokaal<br />4. Schermvergrendeling -&gt; Schermvergrendeling -&gt; Tussen Slapen en Voorkom broekzakgesprekken is geen <br />Optie is niet (langer) beschikbaar:<br />4b. Schermvergrendeling -&gt; Schermvergrendeling -&gt; PIN code -&gt;Voer vier <b>of meer</b> nummers in om apparaat te vergrendelen. = Voer vier nummers in om apparaat te vergrendelen.<br />Meer dan vier cijfers zijn helaas niet mogelijk als pincode.<br />5. Niet storen -&gt; Niets is vertaald.<br />In deze 3 opties is alleen de inhoud van <b>Silence all disturbances </b>vertaald.<br />6. Extra instellingen -&gt; Beveiliging -&gt; <b>Notification access = </b>Notificaties uitlezen<br />7. Extra instellingen -&gt; Beveiliging -&gt; <b>Advanced</b> = Geavanceerd<br />8. Extra instellingen -&gt; Beveiliging -&gt; <b>Apps with usage access</b> = Apps met gebruikstoegang<br />9. Extra instellingen -&gt; <b>Meldingslicht</b> = Notificatie LED<br />10. Extra instellingen -&gt; Meldingslicht -&gt; <b>Knipperen meldings LED</b> = Inschakelen notificatie LED<br />10b. Meldings LED kleur = LED kleur bij meldingen<br />10c. LED kleur bij gesprekken = LED kleur bij operoepen<br />10d. LED licht voor berichten = LED kleur bij berichten<br />11. Extra instellingen -&gt; Knoppen -&gt; <b>Tijsdduur</b> knop licht = Tijdsduur verlichting of tijdsduur lichtknop(pen)<br />11b. Ik twijfel over de benaming van de volgende zaken:<br /><b>Bepaal de lange druk tijd = </b>Vertragingstijd knoppen<br /><b>Knop lichten = </b>Verlichting knoppen<br />12. Extra instellingen -&gt; Knoppen -&gt; Recente = Menu. Als het <b>Recente</b> of <b>Recent</b> moet blijven, dan moet het volgende worden aangepast:<br />Extra instellingen -&gt; Knoppen -&gt;<b>Menu</b>, Home en Terug knop aanduiding verlichten, worden aangepast.<br /><br />13. Extra instellingen -&gt; Toegankelijkheid -&gt; <b>High contrast text (experimental)</b> = Tekst met hoog contrast (experimenteel)<br />14. Extra instellingen -&gt; Toegankelijkheid -&gt; <b>Display</b> = Scherm<br />15. Extra instellingen -&gt; Toegankelijkheid -&gt; <b>Color inversion (Experimental) may affect performance</b> = Kleur inversie (experimenteel) kan invloed hebben op de prestaties<br />17. Extra instellingen -&gt; Toegankelijkheid -&gt;<b> Color correction</b> = Kleurcorrectie<br />17b. Inhoud van Kleurcorrectie moet nog worden vertaald. Hier is de volledige vertaling<br />Deze functie is experimenteel en kan invloed hebben op de prestaties.<br />Correctiemodus<br />Deuteranomalie (rood-groen)<br />Protanomalie (rood-groen)<br />Tritanomalie (blauw-geel)<br />18. Extra instellingen -&gt; Opties voor ontwikkelaars -&gt; <b>Enable view attribute inspection</b> = Inspectie van weergavekenmerk instellen<br />19. Extra instellingen -&gt; Opties voor ontwikkelaars -&gt; <b>Enable Wi-Fi Verbose Logging</b> = Uitgebreide wifi-logregistratie inschakelen.<br /><i>(wifi mag ook Wi-Fi zijn, volgens mij wordt dat door het gehele systeem al gebruikt)</i><br />20. Extra instellingen -&gt; Opties voor ontwikkelaars -&gt; <b>Aggressive Wi-Fi to Celluar handover</b> = Aggressieve handover van wifi naar mobiel<br />21. Extra instellingen -&gt; Opties voor ontwikkelaars -&gt; <b>Always allow Wi-Fi Roam Scans</b> = Altijd roamingscans voor wifi toestaan<br />22. Extra instellingen -&gt; Opties voor ontwikkelaars -&gt; <b>Logger buffer sizes</b> = logger-buffergrootten<br />23. Extra instellingen -&gt; Opties voor ontwikkelaars -&gt; <b>Use NuPlayer (experimental) = </b>Gebruik NuPlayer (experimenteel)<br />23b. <b>Use NuPlayer instead of AwesomePlayer</b> = Gebruik NuPlayer in plaats van AwesomePlayer<br />24. Extra instellingen -&gt; Opties voor ontwikkelaars -&gt; <b>Disable USB audio routing </b>= USB-audiorouting uitschakelen<br />24b. <b>Disable automatix routing to USB audio peripherals</b> = Automatische routing naar USB-randapparatuur uitschakelen<br />25. Mi account -&gt; Mi Cloud xxx dGB <b>overblijvend</b> = Mi Cloud xxx GB beschikbaar<br /><br />Dit was de lijst van instellingen. Laat je ons weten wanneer het (en eventueel welke aanpassingen) is aangepast?<br />Alvast bedankt namens de Nederlands-talige community.

**Comment by MannyRibo** [comment]
Ik heb al best wat hiervan verbeterd na update 5.10.15. Verder zie ik hier veel meer Engelse instellingen tussen staan die ik heb op mijn mi4. Niet storen is bij mij volledig vertaald bijvoorbeeld. Veel andere Engelse tekst ook niet te vinden hier.

**Comment by Cueie** [comment]
Er mee bezig

**Comment by Cueie** [comment]
Ik denk dat je nog eens moet upgraden naar de allerlaatse versie.
Er zijn denkelijk reeds veel fouten opgelost

**Comment by MannyRibo** [comment]
4. Schermvergrendeling -> Schermvergrendeling -> Tussen Slapen en Voorkom broekzakgesprekken is geen .  Hier is een nieuwe instelling bijgekomen waarmee je kan bepalen of het scherm aan moet gaan bij een nieuwe melding. Weet dus niet precies wat je hiermee bedoelt.

5. Niet storen -> Niets is vertaald.
Alles is vertaald op mijn telefoon.

6,7 en 8 ook niet te vinden hier.

10 en 11 toevallig allemaal al fixed paar dagen terug.

12 is een goeie, dat fix ik straks wel eventjes.

13 t/m 24 geen idee waar dat over gaat, niet te vinden op mijn telefoon.

**Comment by Kiswum** [comment]
MannyRibo, ik ging er vanuit dat de Developer mode wel bekend was bij eigenlijk alle geavanceerde Android gebruikers. Tik 8 keer op de Miuiversie in de "about" sectie van je instellingen. Zo kun je die modus activeren.

Het is overigens goed mogelijk dat veel opties niet aanwezig zijn bij veel oudere telefoons. Het staat in het verhaal erbij. Het gaat hier om een Redmi Note 2 Prime met Miui 7. Ik heb inmiddels de laatste release erop staan: 5.10.16

Ter verificatie, de volgende zaken zijn reeds opgelost:
10 is volledig opgelost, ik zie nu zelfs een typo in mijn aangedragen vertaling.
11 is volledig opgelost

4 is opgelost, de optie: "Vergrendelscherm ontwaken voor meldingen", was niet zichtbaar. Alleen de slider was zichtbaar.

Succes met alle verbeteringen. Mocht je een de telefoon nodig hebben voor de diverse "onzichtbare opties", laat het me maar gerust even weten. Als je hier niet direct een reply krijgt. Dan kan het zijn dat ik er geen notificatie van krijg. Ik ben via xiaomi.eu beter bereikbaar of per mail.

**Comment by MannyRibo** [comment]
Ik weet wel wat developer mode is ja. Wat ik bedoelde met dat het niet te vinden is op mijn telefoon is dat ik er dus nooit erg in heb gehad dat er onvertaalde strings zijn. Telefoons van xiaomi met Android 5 hebben waarschijnlijk andere instellingen dan telefoons die nog kitkat draaien. Die opties zijn niet onzichtbaar voor me, deze zijn allemaal prima te vinden in de Engelse repo. Ik zal er een andere keer naar kijken. Waarschijnlijk wel voor vrijdag dus opgelost in de volgende update.

**Comment by Kiswum** [comment]
Welke telefoons gebruiken jullie?
Wellicht kan ik bepaalde zaken nog op mijn Mi2 testen of ik kan van familieleden een Redmi 1 of 1s lenen.
Mogelijk zijn er in Android 5 wat nieuwe zaken toegevoegd aan de instellingen, dit zou inderdaad verklaren dat een aantal features niet zichtbaar zijn.

De Developer mode heeft wat mij betreft de laagste prioriteit, als dat in een andere release wordt uitgepakt, dan vind ik het allang prima.

Via Github krijg ik overigens netjes een update op deze thread per mail toegezonden.

**Comment by MannyRibo** [comment]
Ik heb zelf een mi4. Heb je de Redmi Note 2 Prime nog deze vrijdag? Dan kan je meteen kijken of het allemaal is opgelost en of alle wijzigingen goed zijn doorgevoerd. Ik ga nu aan de slag met alle openstaande punten. Ik laat wat weten als het klaar is of als ik tegen bepaalde dingen aanloop. Bedankt voor het melden!

**Comment by Kiswum** [comment]
Ik zal hem deze vrijdag/zaterdag nog zeker in mijn bezit hebben. Ik zal de wijzigingen dan wel controleren. Bedankt voor het verwerken van de punten.

**Comment by MannyRibo** [comment]
5, 6, 7 en 8 + 13 t/m 25 moeten nog gedaan worden, dat is al die Engelse tekst. De rest is gedaan. De rest wordt vanavond.

**Comment by MannyRibo** [comment]
https://github.com/redmaner/MIUI7-XML-DUTCH/pull/60/files

**Comment by MannyRibo** [comment]
Alle punten verwerkt in laatste commit. Controleer alsjeblieft deze vrijdag als je de update hebt gedaan of alles oke is. Bedankt voor het melden van de fouten!

**Comment by redmaner** [comment]
Zodra Kiswum groen licht geeft kan deze issue gesloten worden.
Goed werk!

**Comment by Kiswum** [comment]
Bedankt voor jullie goede en snelle werk!

Verder blijven alleen de volgende puntjes nog open staan:
5. inhoud van Niet storen is nog niet vertaald. Mogelijk is dit anders bij nieuwere telefoons.

Het volgende zie ik nog staan:
Always allow disturbances
Only allow exceptions
Silence all disturbances

De inhoud van deze zaken is wel vertaald.

10. Meldingslicht blijft vreemd, maar geen echte fout.

**Comment by MannyRibo** [comment]
Dus deze drie regels zijn het enige wat nog niet vertaald is in Do Not Disturb? Daar zal ik naar kijken. 

En meldingslicht, ja in het Engels staat het als notifcation light. Persoonlijk vind ik het niet heel vreemd klinken maar ledlicht zou ook kunnen. Dat is een beetje persoonlijk.

**Comment by Kiswum** [comment]
Klopt helemaal! Dat is het enige wat me zo snel opviel. De overige zaken zijn gewoon in orde.

Notificatie led / meldingslicht. Het is wellicht een persoonlijk voorkeur. In beide gevallen weet je waar het over gaat, dat is het belangrijkste.

**Comment by redmaner** [comment]
Die drie regels zijn een array
Notificatielicht zou ook nog kunnen.

**Comment by Kiswum** [comment]
Ik heb inmiddels weer de beschikking tot mijn Mi2 en daarop zie ik dezelfde "fouten" staan. Na de verkoop van de Redmi Note 2, kan ik jullie blijven voorzien van updates en meer info.

**Comment by MannyRibo** [comment]
Ja die drie regels staan volgens mij in AntiSpam.apk\strings.xml. Ik zal dat nu oplossen.
