### ISSUE TITLE
Melding over nederlandse taal

### ISSUE THREAD

**Issue by rbijlsma** [redmaner/MIUI7-XML-DUTCH#97]
Bij het bijwerken van een app wordt in de notificatielijst nu gemeld "applicatie geupdated" volgens mij kan hier beter komen te staan "applicatie bijgewerkt".

Bij de menu's voor het installeren wordt een aantal knoppen niet correct weergegeven. 
Bijvoorbeeld bij het aanmelden van het Mi account staan twee knoppen niet goed. Er wordt dan getoond:
< u >Wachtwoord vergeten< /u >
< u >Aanmelden met e-mail of Mi account ID< /u >

In het scherm staat ook "Akkoord gaan metGebruikersoverkenkomstenPrivacybeleid" hierbij zijn een aantal woorden zonder spaties geschreven.  

In Dutch/main/XiaomiAccount.apk/res/values-nl/strings.xml staat: < string name="updated_nothing ">Geüpdatet< /string > de waarde kan hier beter zijn 'Bijgewerkt'

**Comment by MannyRibo** [comment]
Dat "applicatie geupdated", komt dat van de play store of als je handmatig met een .apk hebt bijgewerkt? Aan de tekst van play store meldingen kunnen we niks veranderen. 

Deze twee dingen: 

< u >Wachtwoord vergeten< /u >
< u >Aanmelden met e-mail of Mi account ID< /u >

zijn die er ook als je telefoon is ingesteld op Engels?

Akkoord gaan metGebruikersoverkenkomstenPrivacybeleid

Welk scherm staat dat?

**Comment by rbijlsma** [comment]
Bij Engels niet.


Zie bijgevoegde screen shotjes.



Verstuurd door Outlook voor Android





On Sat, Nov 7, 2015 at 5:43 PM -0800, "Manny" <notifications@github.com> wrote:
Dat "applicatie geupdated", komt dat van de play store of als je handmatig met een .apk hebt bijgewerkt? Aan de tekst van play store meldingen kunnen we niks veranderen.

Deze twee dingen:

< u >Wachtwoord vergeten< /u >
< u >Aanmelden met e-mail of Mi account ID< /u >

zijn die er ook als je telefoon is ingesteld op Engels?

Akkoord gaan metGebruikersoverkenkomstenPrivacybeleid

Welk scherm staat dat?

---

**Comment by rbijlsma** [comment]
Het gaat allemaal om het aanmeldscherm van het mi account.


Verstuurd door Outlook voor Android





On Sat, Nov 7, 2015 at 5:43 PM -0800, "Manny" <notifications@github.com> wrote:
Dat "applicatie geupdated", komt dat van de play store of als je handmatig met een .apk hebt bijgewerkt? Aan de tekst van play store meldingen kunnen we niks veranderen.

Deze twee dingen:

< u >Wachtwoord vergeten< /u >
< u >Aanmelden met e-mail of Mi account ID< /u >

zijn die er ook als je telefoon is ingesteld op Engels?

Akkoord gaan metGebruikersoverkenkomstenPrivacybeleid

Welk scherm staat dat?

---

**Comment by MannyRibo** [comment]
Ik kan je screenshots niet zien. Zou helpen bij het oplossen hiervan.

**Comment by rbijlsma** [comment]
Nu is het hopelijk wel gelukt om ze bij te sluiten.

Date: Mon, 9 Nov 2015 15:33:25 -0800

**Comment by MannyRibo** [comment]
Dankjewel. Sorry dat het zo lang heeft moeten duren maar ik denk het opgelost te hebben. A.u.b. met de volgende weekly update kijken of het is opgelost. Bent u nog meer problemen tegengekomen?

**Comment by MannyRibo** [comment]
https://github.com/redmaner/MIUI7-XML-DUTCH/pull/106

**Comment by rbijlsma** [comment]
Bedankt.

Bij de klok zijn ook nog een paar dingen die ik niet zo mooi vind.

- de tekst van de knoppen 'Wekker toevoegen' en 'Instellingen' staan te dicht bij elkaar.
- is het niet mooier om de titel wekkers te veranderen in 'Alarm'
- dan zou je bij de eerste knop de tekst 'Nieuw Alarm' kunnen gebruiken.

![screenshot_2015-11-15-21-24-42_com android deskclock](https://cloud.githubusercontent.com/assets/15678627/11170801/6e0def7e-8bdf-11e5-9435-e3c2d0958264.png)
